// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CreateProducts(ctx context.Context, arg CreateProductsParams) error
	DeleteProduct(ctx context.Context, id int32) (pgconn.CommandTag, error)
	DeleteSessionByToken(ctx context.Context, token string) error
	FindUsername(ctx context.Context, username string) (FindUsernameRow, error)
	GetProductAdmin(ctx context.Context, userID int32) ([]GetProductAdminRow, error)
	SearchToken(ctx context.Context, token string) (string, error)
	SelectUserBySession(ctx context.Context, token string) (int32, error)
	SetToken(ctx context.Context, arg SetTokenParams) (string, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
