// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= NOW()
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredSessions)
	return err
}

const createProducts = `-- name: CreateProducts :exec
INSERT INTO products (nama_products, price, user_id)
VALUES ($1, $2, $3)
`

type CreateProductsParams struct {
	NamaProducts string `json:"nama_products"`
	Price        int32  `json:"price"`
	UserID       int32  `json:"user_id"`
}

func (q *Queries) CreateProducts(ctx context.Context, arg CreateProductsParams) error {
	_, err := q.db.Exec(ctx, createProducts, arg.NamaProducts, arg.Price, arg.UserID)
	return err
}

const deleteProduct = `-- name: DeleteProduct :execresult
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteProduct, id)
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions
WHERE token = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, token)
	return err
}

const findUsername = `-- name: FindUsername :one
SELECT id, username, password FROM users
WHERE username = $1 LIMIT 1
`

type FindUsernameRow struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) FindUsername(ctx context.Context, username string) (FindUsernameRow, error) {
	row := q.db.QueryRow(ctx, findUsername, username)
	var i FindUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const getProductAdmin = `-- name: GetProductAdmin :many
SELECT id, nama_products, price 
FROM products 
WHERE user_id = $1
`

type GetProductAdminRow struct {
	ID           int32  `json:"id"`
	NamaProducts string `json:"nama_products"`
	Price        int32  `json:"price"`
}

func (q *Queries) GetProductAdmin(ctx context.Context, userID int32) ([]GetProductAdminRow, error) {
	rows, err := q.db.Query(ctx, getProductAdmin, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductAdminRow
	for rows.Next() {
		var i GetProductAdminRow
		if err := rows.Scan(&i.ID, &i.NamaProducts, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchToken = `-- name: SearchToken :one
SELECT token FROM sessions
WHERE token = $1 AND expires_at > NOW()
`

func (q *Queries) SearchToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRow(ctx, searchToken, token)
	err := row.Scan(&token)
	return token, err
}

const selectUserBySession = `-- name: SelectUserBySession :one
SELECT user_id FROM sessions
WHERE token = $1 AND expires_at > NOW()
`

func (q *Queries) SelectUserBySession(ctx context.Context, token string) (int32, error) {
	row := q.db.QueryRow(ctx, selectUserBySession, token)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const setToken = `-- name: SetToken :one
INSERT INTO sessions (user_id, token, expires_at)
VALUES ($1, $2, NOW() + INTERVAL '30 days')
RETURNING token, expires_at
`

type SetTokenParams struct {
	UserID int32  `json:"user_id"`
	Token  string `json:"token"`
}

type SetTokenRow struct {
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SetToken(ctx context.Context, arg SetTokenParams) (SetTokenRow, error) {
	row := q.db.QueryRow(ctx, setToken, arg.UserID, arg.Token)
	var i SetTokenRow
	err := row.Scan(&i.Token, &i.ExpiresAt)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    username = COALESCE($1, username),
    password = COALESCE($2, password)
WHERE id = $3
RETURNING id, username
`

type UpdateUserParams struct {
	Username pgtype.Text `json:"username"`
	Password pgtype.Text `json:"password"`
	ID       int32       `json:"id"`
}

type UpdateUserRow struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Username, arg.Password, arg.ID)
	var i UpdateUserRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}
