// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions
WHERE token = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, token)
	return err
}

const findUsername = `-- name: FindUsername :one
SELECT id, username, password FROM users
WHERE username = $1 LIMIT 1
`

type FindUsernameRow struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) FindUsername(ctx context.Context, username string) (FindUsernameRow, error) {
	row := q.db.QueryRow(ctx, findUsername, username)
	var i FindUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const searchToken = `-- name: SearchToken :one
SELECT token FROM sessions
WHERE token = $1
`

func (q *Queries) SearchToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRow(ctx, searchToken, token)
	err := row.Scan(&token)
	return token, err
}

const setToken = `-- name: SetToken :one
INSERT INTO sessions (user_id, token)
VALUES ($1, $2)
RETURNING token
`

type SetTokenParams struct {
	UserID int32  `json:"user_id"`
	Token  string `json:"token"`
}

func (q *Queries) SetToken(ctx context.Context, arg SetTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, setToken, arg.UserID, arg.Token)
	var token string
	err := row.Scan(&token)
	return token, err
}
