// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	DeleteSessionByToken(ctx context.Context, token string) error
	FindUsername(ctx context.Context, username string) (FindUsernameRow, error)
	SearchToken(ctx context.Context, token string) (string, error)
	SetToken(ctx context.Context, arg SetTokenParams) (string, error)
}

var _ Querier = (*Queries)(nil)
